### ISSUE TITLE
How is "solos_3_latent_concept_sgd_epoch_10000_lr_10.0_model.npy" obtained?

### ISSUE THREAD

**Issue by SWXxing** [rxtan2/AVSeT#2]
When running the train_bimodal_cyclic_losses_solos_scc.sh command,
OPTS+="--latent_concept_path ./precomputed_features/latent_features/solos_3_latent_concept_sgd_epoch_10000_lr_10.0_model.npy"
How is "solos_3_latent_concept_sgd_epoch_10000_lr_10.0_model.npy" obtained here?
Run python extract_latent_concepts_main.py directly?

**Comment by rxtan2** [comment]
Hi! Yes, you can run that script to extract latent captions. If you are running on more complex frames, it may be important to use more learnable parameters.

**Comment by slliugit** [comment]
when running extract_latent_concepts_main.py，it occurs
'''
File "/home/AVSeT-main/extract_latent_concepts_main.py", line 60, in main
    model = ClipLatentModel()
  File "/home/AVSeT-main/models/clip_latent_models.py", line 550, in __init__
    counts: list = [len(set(k.split(".")[2] for k in state_dict if k.startswith(f"visual.layer{b}"))) for b in [1, 2, 3, 4]]
  File "/home/AVSeT-main/models/clip_latent_models.py", line 550, in <listcomp>
    counts: list = [len(set(k.split(".")[2] for k in state_dict if k.startswith(f"visual.layer{b}"))) for b in [1, 2, 3, 4]]
NameError: name 'state_dict' is not defined
'''

**Comment by slliugit** [comment]
when running extract_latent_concepts_main.py，it occurs
'''
File "/home/AVSeT-main/extract_latent_concepts_main.py", line 60, in main
    model = ClipLatentModel()
  File "/home/AVSeT-main/models/clip_latent_models.py", line 550, in __init__
    counts: list = [len(set(k.split(".")[2] for k in state_dict if k.startswith(f"visual.layer{b}"))) for b in [1, 2, 3, 4]]
  File "/home/AVSeT-main/models/clip_latent_models.py", line 550, in <listcomp>
    counts: list = [len(set(k.split(".")[2] for k in state_dict if k.startswith(f"visual.layer{b}"))) for b in [1, 2, 3, 4]]
NameError: name 'state_dict' is not defined
'''
